pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('java_project') {
                    sh '/usr/bin/mvn clean package'
                }
            }
        }
    }
}
